/**
 * Renders the human-readable block reference Markdown from the registry. Pure
 * and deterministic (no clock, no IO) so the {@link ../scripts/genBlockReference}
 * script and the drift-guard test can both call it and agree. Every fact comes
 * from {@link ./blockBehavior}, so the doc cannot drift from the live behavior.
 */
import { behaviorSummary, streamEffect, type StreamEffect } from './blockBehavior';
import { blockSpecs } from './blockSpecs';

/** Effect groups in presentation order, with their section headings. */
const SECTIONS: ReadonlyArray<{ effect: StreamEffect; title: string }> = [
  { effect: 'source', title: 'Sources' },
  { effect: 'enrich', title: 'Enrichment' },
  { effect: 'transform', title: 'Transforms' },
  { effect: 'export', title: 'Exports' },
  { effect: 'annotation', title: 'Annotations' }
];

export function renderBlockReference(): string {
  const sections = SECTIONS.map(renderSection).filter((block) => block.length > 0);
  return [
    '# Block Reference',
    '',
    'Generated by `npm run docs:blocks` from `src/shared/blockSpecs.ts`. Do not edit by hand.',
    '',
    sections.join('\n')
  ].join('\n');
}

function renderSection({ effect, title }: { effect: StreamEffect; title: string }): string {
  const entries = blockSpecs.filter((spec) => streamEffect(spec.type) === effect).map(renderEntry);
  if (entries.length === 0) {
    return '';
  }
  return [`## ${title}`, '', entries.join('\n')].join('\n');
}

function renderEntry(spec: (typeof blockSpecs)[number]): string {
  const summary = behaviorSummary(spec.type);
  const lines = [
    `### ${spec.label} · \`${spec.type}\``,
    '',
    `- **Effect:** ${summary.label}`,
    `- **In → Out:** ${summary.inLabel} → ${summary.outLabel}`,
    `- **Purpose:** ${summary.description}`
  ];
  if (summary.fanOut) {
    lines.push('- **Fan-out:** one CLI call per upstream item when the bound field is blank.');
  }
  if (summary.note) {
    lines.push(`- **Note:** ${summary.note}`);
  }
  lines.push('');
  return lines.join('\n');
}
