import { PROVIDER_META } from './providers';
import { REDDIT_LOGO_DATA_URI } from './redditLogo';
import type { SocialItem } from './types';
import { safeHref } from './urlSafety';
import { coerceFiniteNumber } from './values';

export { safeHref } from './urlSafety';

export interface HtmlReportMeta {
  /** Flow name shown in the report header. */
  flowName: string;
  /** ISO timestamp the report was generated; caller supplies (engine run time). */
  generatedAt: string;
}

/**
 * Escape the five HTML-significant characters. Applied to EVERY interpolated
 * text value, because the report embeds attacker-influenceable fetched content
 * (titles, bodies, authors, communities, URLs). Ampersand is replaced first so
 * the entities introduced by the later replacements are not double-encoded.
 */
export function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

const IMAGE_EXTENSION = /\.(png|jpe?g|gif|webp|avif|bmp|svg)(\?|#|$)/i;
const PLATFORM_LABEL: Record<SocialItem['platform'], string> = {
  reddit: PROVIDER_META.reddit.badge,
  twitter: PROVIDER_META.twitter.badge
};

// Brand marks are inlined as static SVG (no untrusted input), so they need no
// escaping. `fill="currentColor"` lets CSS tint each mark per context. The
// Reddit Snoo is a full-color raster (REDDIT_LOGO_DATA_URI) painted as a CSS
// background, so its badge/stat slots carry no inline markup here.
const X_LOGO =
  '<svg viewBox="0 0 24 24" aria-hidden="true" fill="currentColor"><path d="M18.901 1.153h3.68l-8.04 9.19L24 22.846h-7.406l-5.8-7.584-6.638 7.584H.474l8.6-9.83L0 1.154h7.594l5.243 6.932ZM17.61 20.644h2.039L6.486 3.24H4.298Z"/></svg>';
const REDDIX_MARK =
  '<svg viewBox="0 0 24 24" fill="none" stroke="#fff" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="6" cy="7" r="2.4"/><circle cx="6" cy="17" r="2.4"/><circle cx="18" cy="12" r="2.4"/><path d="M8.3 7h3.2a3 3 0 0 1 3 3M8.3 17h3.2a3 3 0 0 0 3-3"/></svg>';

const PLATFORM_LOGO: Record<SocialItem['platform'], string> = {
  reddit: '',
  twitter: X_LOGO
};

/**
 * Serialize normalized items into ONE self-contained HTML document: inline
 * styles + inline vanilla JS, no external assets, so it opens from `file://`.
 * All untrusted content is escaped once here at generation time; the embedded
 * script only filters/sorts the already-rendered DOM (it never templates), so
 * no escaping happens client-side.
 */
export function serializeHtml(items: SocialItem[], meta: HtmlReportMeta): string {
  const total = items.length;
  const redditCount = items.filter((item) => item.platform === 'reddit').length;
  const twitterCount = items.filter((item) => item.platform === 'twitter').length;
  const flowName = escapeHtml(meta.flowName);
  const generated = escapeHtml(parseDate(meta.generatedAt).display);

  const cards = items.map(renderCard).join('\n');
  const emptyState = total === 0 ? '<div class="empty" id="empty">No items in this report.</div>' : '';

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta name="robots" content="noindex" />
<title>${flowName} — Reddix Report</title>
<style>${STYLES}</style>
</head>
<body>
<header class="report-head" data-total="${total}" data-reddit="${redditCount}" data-twitter="${twitterCount}">
  <div class="head-top">
    <div class="brand">
      <span class="brand-mark">${REDDIX_MARK}</span>
      <div class="brand-text">
        <span class="brand-name">Reddix Report</span>
        <h1>${flowName}</h1>
      </div>
    </div>
    <span class="generated">Generated ${generated}</span>
  </div>
  <div class="stats">
    <span class="stat stat-total"><b>${total}</b> ${total === 1 ? 'result' : 'results'}</span>
    <span class="stat stat-reddit"><span class="stat-logo"></span><b>${redditCount}</b> reddit</span>
    <span class="stat stat-x"><span class="stat-logo">${X_LOGO}</span><b>${twitterCount}</b> x</span>
  </div>
  <div class="controls">
    <input id="q" class="search" type="search" placeholder="Search results…" aria-label="Search results" />
    <label class="ctl">Platform
      <select id="platform" aria-label="Filter by platform">
        <option value="all">All</option>
        <option value="reddit">Reddit</option>
        <option value="twitter">X</option>
      </select>
    </label>
    <label class="ctl">Sort
      <select id="sort" aria-label="Sort results">
        <option value="date">Newest</option>
        <option value="score">Top score</option>
      </select>
    </label>
  </div>
</header>
<main id="grid" class="grid">
${cards}
</main>
${emptyState}
<div class="empty" id="noMatch" hidden>No results match your filters.</div>
<footer class="report-foot"><span class="foot-mark">${REDDIX_MARK}</span> Generated by Reddix</footer>
<script>${SCRIPT}</script>
</body>
</html>`;
}

function renderCard(item: SocialItem): string {
  const { display: dateDisplay, epoch } = parseDate(item.createdAt);
  const handle = escapeHtml(originLabel(item));
  const title = item.platform === 'reddit' ? item.title : null;
  const bodyText = item.platform === 'reddit' ? item.body : item.text;
  const score = sortScoreForItem(item);

  const platformLabel = escapeHtml(PLATFORM_LABEL[item.platform]);
  const logo = PLATFORM_LOGO[item.platform];
  const titleHtml = title ? `<h2 class="card-title">${escapeHtml(title)}</h2>` : '';
  const bodyHtml = bodyText ? `<p class="card-body">${escapeHtml(bodyText)}</p>` : '';
  const href = safeHref(item.url);
  const linkHtml = href
    ? `<a class="card-link" href="${escapeHtml(href)}" target="_blank" rel="noopener noreferrer nofollow">open original ↗</a>`
    : '';

  return `<article class="card platform-${item.platform}" data-platform="${item.platform}" data-score="${score ?? 0}" data-date="${epoch}">
  <div class="card-head">
    <span class="badge badge-${item.platform}" title="${platformLabel}" aria-label="${platformLabel}">${logo}</span>
    <span class="handle">${handle}</span>
    <time class="card-date">${escapeHtml(dateDisplay)}</time>
  </div>
  ${imageThumb(item.media)}
  ${titleHtml}
  ${bodyHtml}
  <div class="card-foot">
    <span class="engagement">${renderEngagement(item)}</span>
    ${linkHtml}
  </div>
</article>`;
}

function originLabel(item: SocialItem): string {
  if (item.platform === 'reddit') {
    if (item.community) {
      return `r/${item.community}`;
    }
    return item.author ? `u/${item.author}` : 'reddit';
  }
  return item.author ? `@${item.author}` : 'x';
}

function renderEngagement(item: SocialItem): string {
  const parts: string[] = [];
  if (item.platform === 'reddit') {
    pushMetric(parts, '↑', item.engagement.score, 'score');
    pushMetric(parts, '💬', item.engagement.comments, 'comments');
  } else {
    pushMetric(parts, '♥', item.engagement.likes, 'likes');
    pushMetric(parts, '🔁', item.engagement.retweets, 'retweets');
    pushMetric(parts, '👁', item.engagement.views, 'views');
  }
  return parts.join('');
}

function pushMetric(parts: string[], icon: string, raw: unknown, label: string): void {
  const value = coerceNumber(raw);
  if (value === null) {
    return;
  }
  parts.push(`<span class="metric" title="${label}">${icon} ${escapeHtml(formatCount(value))}</span>`);
}

function imageThumb(media: SocialItem['media']): string {
  const first = media[0];
  if (!first) {
    return '';
  }
  const href = safeHref(first.url);
  if (!href) {
    return '';
  }
  const isImage = first.type === 'image' || IMAGE_EXTENSION.test(href);
  if (!isImage) {
    return '';
  }
  return `<img class="card-media" loading="lazy" alt="" src="${escapeHtml(href)}" />`;
}

const coerceNumber = coerceFiniteNumber;

function sortScoreForItem(item: SocialItem): number | null {
  if (item.platform === 'reddit') {
    return coerceNumber(item.engagement.score);
  }
  return coerceNumber(item.engagement.likes) ?? coerceNumber(item.engagement.views);
}

function formatCount(value: number): string {
  // Thresholds are nudged below each round boundary (999_950, not 1_000_000) so a
  // value like 999_999 rolls over to "1.0M" instead of rounding to a nonsensical
  // "1000.0k" inside the lower unit's branch.
  const abs = Math.abs(value);
  if (abs >= 999_950_000) {
    return `${(value / 1_000_000_000).toFixed(1)}B`;
  }
  if (abs >= 999_950) {
    return `${(value / 1_000_000).toFixed(1)}M`;
  }
  if (abs >= 1_000) {
    return `${(value / 1_000).toFixed(1)}k`;
  }
  return String(value);
}

function parseDate(iso: string): { display: string; epoch: number } {
  const date = new Date(iso);
  const epoch = date.getTime();
  if (Number.isNaN(epoch)) {
    return { display: iso, epoch: 0 };
  }
  const pad = (value: number): string => String(value).padStart(2, '0');
  const display = `${date.getUTCFullYear()}-${pad(date.getUTCMonth() + 1)}-${pad(date.getUTCDate())} ${pad(
    date.getUTCHours()
  )}:${pad(date.getUTCMinutes())} UTC`;
  return { display, epoch };
}

const STYLES = `
:root{--bg:#0a0c11;--panel:#141821;--panel-2:#1a1f2b;--line:#232a38;--line-hi:#33405a;--text:#e8ebf2;--muted:#8c95a8;--muted-2:#aeb6c7;--reddit:#ff4500;--x:#1d9bf0;--accent:#7c9cff;--radius:14px;--shadow:0 1px 2px rgba(0,0,0,.45),0 12px 28px -16px rgba(0,0,0,.7);--reddit-logo:url("${REDDIT_LOGO_DATA_URI}")}
*{box-sizing:border-box}
html{color-scheme:dark}
body{margin:0;background:radial-gradient(1200px 620px at 82% -12%,#1a2030 0,var(--bg) 58%) fixed;color:var(--text);font:15px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;-webkit-font-smoothing:antialiased}
svg{display:block}
.report-head{position:sticky;top:0;z-index:5;padding:18px 24px 16px;background:rgba(10,12,17,.78);backdrop-filter:blur(14px) saturate(140%);border-bottom:1px solid var(--line)}
.head-top{display:flex;align-items:center;justify-content:space-between;gap:16px;flex-wrap:wrap}
.brand{display:flex;align-items:center;gap:12px;min-width:0}
.brand-mark{display:grid;place-items:center;width:38px;height:38px;border-radius:11px;background:linear-gradient(150deg,#ff5b1a,#ff4500 58%,#e03e00);box-shadow:0 4px 14px -4px rgba(255,69,0,.55),inset 0 1px 0 rgba(255,255,255,.25);flex:none}
.brand-mark svg{width:21px;height:21px}
.brand-text{display:flex;flex-direction:column;min-width:0}
.brand-name{font-size:11px;font-weight:700;letter-spacing:.14em;text-transform:uppercase;color:var(--reddit)}
.report-head h1{margin:1px 0 0;font-size:19px;font-weight:650;letter-spacing:-.01em;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:46vw}
.generated{color:var(--muted);font-size:12.5px;white-space:nowrap}
.stats{display:flex;gap:8px;margin:14px 0;flex-wrap:wrap}
.stat{display:inline-flex;align-items:center;gap:7px;background:var(--panel);border:1px solid var(--line);padding:6px 12px;border-radius:999px;color:var(--muted);font-size:12.5px}
.stat b{color:var(--text);font-weight:680;font-size:13.5px}
.stat-logo{display:grid;place-items:center;width:15px;height:15px}
.stat-logo svg{width:100%;height:100%}
.stat-reddit .stat-logo{background:var(--reddit-logo) center/cover no-repeat;border-radius:4px}
.stat-reddit b{color:var(--reddit)}
.stat-x .stat-logo{color:var(--text)}
.stat-x b{color:var(--x)}
.controls{display:flex;gap:10px;flex-wrap:wrap;align-items:center}
.search{flex:1 1 240px;min-width:160px;background:var(--panel);border:1px solid var(--line);color:var(--text);padding:10px 14px;border-radius:11px;font-size:14px;outline:none;transition:border-color .15s,box-shadow .15s}
.search::placeholder{color:var(--muted)}
.search:focus{border-color:var(--accent);box-shadow:0 0 0 3px rgba(124,156,255,.15)}
.ctl{display:flex;align-items:center;gap:6px;color:var(--muted);font-size:12.5px}
.ctl select{background:var(--panel);border:1px solid var(--line);color:var(--text);padding:9px 11px;border-radius:11px;font-size:13px;outline:none;cursor:pointer}
.ctl select:focus{border-color:var(--accent)}
.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(310px,1fr));gap:16px;padding:22px 24px;max-width:1440px;margin:0 auto}
.card{position:relative;background:linear-gradient(180deg,var(--panel) 0,var(--panel-2) 100%);border:1px solid var(--line);border-radius:var(--radius);padding:15px 17px;display:flex;flex-direction:column;gap:9px;overflow:hidden;transition:border-color .16s,transform .16s,box-shadow .16s}
.card::before{content:"";position:absolute;inset:0 0 auto 0;height:3px;opacity:.9}
.platform-reddit::before{background:linear-gradient(90deg,var(--reddit),transparent 75%)}
.platform-twitter::before{background:linear-gradient(90deg,var(--x),transparent 75%)}
.card:hover{border-color:var(--line-hi);transform:translateY(-2px);box-shadow:var(--shadow)}
.card-head{display:flex;align-items:center;gap:9px;font-size:12.5px;color:var(--muted)}
.badge{display:grid;place-items:center;width:28px;height:28px;border-radius:9px;color:#fff;flex:none;box-shadow:inset 0 1px 0 rgba(255,255,255,.18)}
.badge svg{width:16px;height:16px}
.badge-reddit{background:var(--reddit-logo) center/cover no-repeat}
.badge-twitter{background:#000;box-shadow:inset 0 0 0 1px #2c3340}
.handle{color:var(--text);font-weight:560;font-size:13px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.card-date{margin-left:auto;color:var(--muted);font-size:11.5px;white-space:nowrap;flex:none}
.card-media{width:100%;max-height:210px;object-fit:cover;border-radius:11px;border:1px solid var(--line)}
.card-title{margin:2px 0 0;font-size:15.5px;font-weight:640;line-height:1.34;letter-spacing:-.005em}
.card-body{margin:0;color:var(--muted-2);font-size:13.5px;line-height:1.5;white-space:pre-wrap;word-break:break-word;display:-webkit-box;-webkit-line-clamp:6;-webkit-box-orient:vertical;overflow:hidden}
.card-foot{margin-top:auto;padding-top:10px;border-top:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;gap:10px}
.engagement{display:flex;gap:8px;color:var(--muted);font-size:12.5px;flex-wrap:wrap}
.metric{display:inline-flex;align-items:center;gap:4px;white-space:nowrap;background:var(--panel-2);border:1px solid var(--line);padding:2px 8px;border-radius:999px}
.card-link{color:var(--accent);text-decoration:none;font-size:12.5px;font-weight:580;white-space:nowrap}
.card-link:hover{text-decoration:underline}
.empty{text-align:center;color:var(--muted);padding:64px 20px;font-size:15px}
.report-foot{display:flex;align-items:center;justify-content:center;gap:7px;padding:22px;color:var(--muted);font-size:12px;border-top:1px solid var(--line)}
.foot-mark{display:grid;place-items:center;width:18px;height:18px;border-radius:5px;background:var(--reddit);flex:none}
.foot-mark svg{width:11px;height:11px}
@media (max-width:560px){.grid{grid-template-columns:1fr;padding:16px}.report-head{padding:14px 16px}.report-head h1{max-width:60vw}}
`;

const SCRIPT = `
(function(){
  var grid=document.getElementById('grid');
  if(!grid)return;
  var search=document.getElementById('q');
  var sortSel=document.getElementById('sort');
  var platSel=document.getElementById('platform');
  var noMatch=document.getElementById('noMatch');
  var cards=Array.prototype.slice.call(grid.querySelectorAll('.card'));
  function apply(){
    var q=(search.value||'').trim().toLowerCase();
    var plat=platSel.value;
    var sort=sortSel.value;
    var visible=[];
    cards.forEach(function(card){
      var okPlat=plat==='all'||card.getAttribute('data-platform')===plat;
      var okText=!q||card.textContent.toLowerCase().indexOf(q)!==-1;
      var show=okPlat&&okText;
      card.style.display=show?'':'none';
      if(show)visible.push(card);
    });
    visible.sort(function(a,b){
      if(sort==='score')return Number(b.getAttribute('data-score'))-Number(a.getAttribute('data-score'));
      return Number(b.getAttribute('data-date'))-Number(a.getAttribute('data-date'));
    });
    visible.forEach(function(card){grid.appendChild(card);});
    if(noMatch)noMatch.hidden=cards.length===0||visible.length>0;
  }
  search.addEventListener('input',apply);
  sortSel.addEventListener('change',apply);
  platSel.addEventListener('change',apply);
  apply();
})();
`;
